![imagen](./img/ejercicios.png)

In [337]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [340]:
my_array = np.arange(0,10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [355]:
my_array[-1::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [350]:
my_array[-2:-4:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [358]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [371]:
ej_4 = np.arange(1,21)
ej_4 = np.reshape(ej_4, (4, 5))
print(ej_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [374]:
ej_4 = ej_4[::-1, ::-1]

In [364]:
print(ej_4)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [366]:
ej_4[-1:-3:-1, -1:-3:-1]

array([[1, 2],
       [6, 7]])

In [367]:
ej_4[:2, :2]

array([[20, 19],
       [15, 14]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [370]:
print(ej_4)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [369]:
ej_4[-1::-2, -1::-2]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [373]:
ej_4[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [388]:
ej_4

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [392]:
ej_4[3:0:-1, ::]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [401]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x[(x == "Loro") | (x == "Perro")]

array(['Loro', 'Perro', 'Loro', 'Perro'], dtype='<U5')

In [402]:
x[[True, True, False, True, True]]

array(['Loro', 'Perro', 'Loro', 'Perro'], dtype='<U5')

In [396]:
Loro = np.where(x == "Loro")
print(x[Loro])

['Loro' 'Loro']


In [397]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [403]:
np.extract(x == "Loro", x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [405]:
ej_9 = np.arange(0,20)
print(ej_9)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [406]:
ej_9 = np.reshape(ej_9, (2, 5, 2))

In [407]:
print(ej_9)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [408]:
ej_4

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [411]:
ej_4 = ej_4[::-1, ::-1]

In [412]:
print(ej_4)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [417]:
ej_11 = np.zeros(10)
print(ej_11)
print(ej_11.nbytes)
ej_11[3] = 1
print(ej_11)
print(ej_11.nbytes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
80


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [420]:
ej_12 = np.arange(10,50)
print(ej_12)
print(ej_12[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [422]:
vector = np.array([1,2,0,0,4,0])
ej_13 = np.nonzero(vector)
print(ej_13)

(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [426]:
ej_14 = np.random.randint(0, 100, size=(10,10))
print(ej_14)
print(np.min(ej_14))
print(np.max(ej_14))

[[40 68  8 79 10 79 51 91 74 58]
 [11 37 69  2 18 17 29 28 53 73]
 [63 28 62 38 62  2 22 94 44 52]
 [35 92 75 45 95 79 27 70 76 40]
 [45 21 64 25 41 58 40 10 66 91]
 [ 9 17  6 40 68 55 68 71  8 11]
 [54 47 45 81 38 56 74 47 24 98]
 [37 28  5 68 49 67 60 95 37 77]
 [14 19 79 82 81 92 58 51  1 30]
 [19 12  9  2 65  7 44 21 34 81]]
1
98


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [429]:
ej_15 = np.random.randint(0,30, size=30)
print(ej_15)
print(np.mean(ej_15))

[ 8 21 15  3  6 24  9  1  1 23 26  0 21 15 23 12  4 17  3 25  7  7 13 21
 25 10  1  4  0  0]
11.5


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [431]:
ej_16 = np.ones((5,5))
print(ej_16)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [446]:
ej_16[1:-1, 1:-1] = 0
ej_16

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [447]:
ej_16 = np.zeros((5,5))
print(ej_16)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [450]:
ej_16[:1:, ::] = 1
ej_16[::, :1:] = 1
ej_16[-1::, ::] = 1
ej_16[::, -1::] = 1


print(ej_16)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [458]:
ej_17 = np.ones((8,8))
print(ej_17)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [459]:
ej_17[1::2, 1::2] = 0
print(ej_17)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [460]:
ej_17[::2, ::2] = 0
print(ej_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [468]:
## Con bucle
ej_17 = np.zeros((8,8))
print(ej_17)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [470]:
for i in range(len(ej_17)):
    for j in range(len(ej_17[i])):
        if (i %2 == 0 and j %2 != 0) or (i %2 != 0 and j %2 == 0):
            ej_17[i,j] = 1
print(ej_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Con bucles otra forma
ejer_17 = np.ones([8,8])

for i in range(len(ejer_17)):
    for j in range(len(ejer_17[i])):
        if i % 2 != 0: 
            if j % 2 != 0 :
                ejer_17[i][j] = 0
        elif i % 2 == 0:
            if j % 2 == 0:
                ejer_17[i][j] = 0

print(ejer_17)

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [478]:
ej_18 = np.array(([0,1], [1,0]), dtype= float)
np.tile(ej_18, (4, 4))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [482]:
ej_19 = np.random.randint(0,25, size=(5,5))
print(ej_19)

normalized = (ej_19 - (np.mean(ej_19))) / np.std(ej_19)
print(normalized)

[[11  2 19 16 21]
 [15  7  0  6  7]
 [11 16  5 22 18]
 [20 21 22 16  2]
 [18 14  2 20 21]]
[[-0.31702891 -1.56845883  0.79535324  0.37820993  1.07344877]
 [ 0.23916216 -0.87321999 -1.84655437 -1.01226776 -0.87321999]
 [-0.31702891  0.37820993 -1.15131553  1.21249654  0.65630547]
 [ 0.93440101  1.07344877  1.21249654  0.37820993 -1.56845883]
 [ 0.65630547  0.10011439 -1.56845883  0.93440101  1.07344877]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [488]:
ej_20 = np.arange(0,11)

ej_20[(ej_20 >3) & (ej_20 < 8)] = -1

print(ej_20)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [496]:
ej_20 = np.arange(0,11)

ej_20[(ej_20 >3) & (ej_20 < 8)] *= -1

print(ej_20)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
